<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    
    $_gdHelper = $this->helper('groupdeals');
    $_groupdeal = $this->getGroupdeal();
    	
	$_merchant = $this->getMerchant($_groupdeal);
    $addressCollection = $this->getAddressCollection($_merchant);
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<!-- google maps scripts -->
<script type="text/javascript" src="<?php if (Mage::app()->getStore()->isCurrentlySecure()): ?>https<?php else: ?>http<?php endif; ?>://maps.googleapis.com/maps/api/js?key=AIzaSyBrKexpYsY6gqoCB1LRUiEIb3LejdvlHRM"></script>
<script type="text/javascript">  
//<![CDATA[
	Event.observe(window, 'load', function() { 	
		<?php if ($_merchant->getStatus()==1 && count($addressCollection)>0): ?>	
  			initializeGoogleMaps();
  			<?php if ($addressCollection[0]!=''): ?>codeAddress('<?php echo $addressCollection[0]; ?>', 'A', '<?php echo $this->getSkinUrl('groupdeals/images'); ?>');<?php endif; ?>
		<?php endif; ?>
	});
//]]>
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view gd-view">
    <div class="product-essential">
	    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	        <div class="no-display">
	            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
	            <input type="hidden" name="related_product" id="related-products-field" value="" />
	        </div>    		   
	        <div class="product-name">
	            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
	        </div>		
	        <div class="gd-product-img-box">
	            <?php echo $this->getChildHtml('media') ?>
	        </div>   
	        <div class="gd-product-shop <?php if ($_product->isVirtual() && $_gdHelper->allowGiveAsGift() && $_product->isSaleable()): ?>gd-gift<?php endif; ?>">        
	            <?php echo $this->getChildHtml('alert_urls') ?>
	            <?php echo $this->getChildHtml('product_type_data') ?>
	            <?php echo $this->getChildHtml('extrahint') ?>
	            
				<!-- add to/prices block -->
				<div class="gd-product-shop-left">
					<div class="gd-add-to-box">
						<div class="gd-buy">
							<div class="gd-buy-shadow"></div>
		            		<?php 
		            			$taxDisplayType = Mage::getStoreConfig('tax/display/type'); 
		            			$specialPrice = $_gdHelper->getFormatedPrice($_product, $_product->getFinalPrice());
		            		?>
							<div class="special-price <?php if (strlen(preg_replace( '/[^0-9]/', '', $specialPrice))>4): ?>small-price<?php endif; ?>" id="<?php if ($taxDisplayType==1): ?>product-price-<?php else: ?>price-including-tax-<?php endif; ?><?php echo $_product->getId(); ?>"><?php echo $specialPrice; ?></div>
							<div class="gd-add-to-cart">						
							    <input type="button" value="<?php if($_product->isSaleable()): ?><?php echo $this->__('Buy!'); ?><?php else: ?><?php echo $this->__('Ended'); ?><?php endif; ?>" class="gd-button<?php if(!$_product->isSaleable()): ?> disabled<?php endif; ?>" <?php if($_product->isSaleable()): ?>onclick="productAddToCartForm.submit(this)"<?php else: ?>disabled="disabled"<?php endif; ?> />
							</div>  				
						</div>
						<div class="gd-box">
							<small><?php echo $this->__('Value') ?></small><br/>
							<span id="old-price-<?php echo $_product->getId(); ?>"><?php echo $_gdHelper->getFormatedPrice($_product, $_product->getPrice()); ?></span>
						</div>
						<div class="gd-box">
							<small><?php echo $this->__('Discount') ?></small><br/>
							<span id="discount-<?php echo $_product->getId(); ?>"><?php echo $this->getDiscountPercent($_product); ?></span>
						</div>
						<div class="gd-box">
							<small><?php echo $this->__('You Save') ?></small><br/>
							<span id="you-save-<?php echo $_product->getId(); ?>"><?php echo $_gdHelper->getFormatedPrice($_product, ($_product->getPrice()-$_product->getFinalPrice())); ?></span>
						</div>
						<?php echo $this->getChildHtml('occ') ?>
						<?php if ($_product->isVirtual() && $_gdHelper->allowGiveAsGift() && $_product->isSaleable()): ?>
						<div class="give-as-gift">
							<button type="button" title="<?php echo $this->__('Give as a Gift') ?>" class="gd-button" onclick="submitProductAddToCartFormGift();"><span><span><?php echo $this->__('Give as a Gift') ?></span></span></button>
						</div>	
						<?php endif; ?>
		            </div>     
		            
		            <!-- custom options block -->     
					<?php if ($_product->isSaleable() && $this->hasOptions()):?>
						<?php echo $this->getChildChildHtml('container', '', true, true) ?>
					<?php endif;?>
					
					<!-- countdown block -->
					<!-- if product isn't saleable set countdown to 00:00:00 -->
					<?php $finished = ($_product->isSaleable()) ? false : true; ?>
					<div class="countdown-box">
						<small><?php echo $this->__('TIME LEFT TO BUY') ?></small>
						<?php echo $_gdHelper->getCountdown($_product->getGroupdealDatetimeTo(), $_product->getId(), $finished); ?>
					</div>
				</div>
							
				<div class="gd-product-shop-right">
					<!-- target/share blocks -->
		            <?php echo $this->getChildHtml('target') ?>	
		            <?php echo $this->getChildHtml('share') ?>		
					
					<!-- add to wishlist/compare block + extra buttons block -->
		            <?php echo $this->getChildHtml('addto') ?>
		            <?php echo $this->getChildHtml('extra_buttons') ?>
		            <?php echo $this->getChildHtml('other') ?>            
				</div>		
			</div>		
	        <div class="gd-product-details">
				<div class="details-box">
					<h2><?php echo $this->__('The Fine Print'); ?></h2>
					<?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_product->getGroupdealFineprint(), 'groupdeal_fineprint') ?>
				</div>
				<div class="details-box">
					<h2><?php echo $this->__('Highlights'); ?></h2>
					<?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_product->getGroupdealHighlights(), 'groupdeal_highlights') ?>
				</div>  
			</div>  
	    </form>
    </div>    
    <div class="gd-product-collateral gd-toggle-content tabs">
        <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
            <dl id="collateral-tabs" class="collateral-tabs">
				<?php if ($_merchant->getStatus()==1 || $this->hasVisibleFrontendAttributes()): ?>
	                <dt class="tab" onclick="reinitGoogleMaps();"><span><?php if ($_merchant->getStatus()==1): ?><?php echo $this->__('Merchant info'); ?><?php else: ?><?php echo $this->__('Additional Info'); ?><?php endif; ?></span></dt>
	                <dd class="tab-container">
	                    <div class="tab-content">
	                    	<?php //echo $this->getChildHtml('additional') ?>	  
							<div class="merchant-info">
								<div class="description-box">	
									<?php if ($_merchant->getStatus()==1): ?>
										<?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($this->getMerchantDescription()); ?>
										<?php if ($this->getBusinessHours()!=''): ?>
											<h2><?php echo $this->__('Business Hours'); ?></h2>
											<?php echo $this->getBusinessHours(); ?>
										<?php endif; ?>
									<?php endif; ?>
									<?php if ($this->hasVisibleFrontendAttributes()): ?>
	        							<?php echo $this->getChildHtml('attributes') ?>
									<?php endif; ?>
								</div>
								<?php if ($_merchant->getStatus()==1): ?>
									<div class="gd-information-box">
										<h2><?php echo $this->getMerchantName(); ?></h2>
										<?php if ($this->getMerchantLogo()!=''): ?>
											<div class="logo">
												<img src="<?php echo $this->getMerchantLogo(); ?>" width="190px" alt="" />
											</div>
										<?php endif; ?>
										<div class="social-links">
											<?php if ($this->getWebsite()!=''): ?><a href="<?php echo $this->getWebsite(); ?>" target="blank"><?php echo $this->__('Company Website'); ?></a><br/><?php endif; ?>
											<?php if ($this->getFacebook()!=''): ?><a href="<?php echo $this->getFacebook(); ?>" target="blank"><?php echo $this->__('Facebook'); ?></a><br/><?php endif; ?>
											<?php if ($this->getTwitter()!=''): ?><a href="<?php echo $this->getTwitter(); ?>" target="blank"><?php echo $this->__('Twitter'); ?></a><br/><?php endif; ?>
											<?php if ($this->getEmail()!=''): ?><a href="mailto:<?php echo $this->getEmail(); ?>"><?php echo $this->__('Email'); ?></a><br/><?php endif; ?>
											<?php if ($this->getPhone()!=''): ?><b><?php echo $this->__('Phone:'); ?></b> <?php echo $this->getPhone(); ?><br/><?php endif; ?>
											<?php if ($this->getMobile()!=''): ?><b><?php echo $this->__('Mobile:'); ?></b> <?php echo $this->getMobile(); ?><br/><?php endif; ?>
										</div>
										<?php $i = 'A'; ?>
										<?php if (count($addressCollection)>0): ?>
											<div id="map_canvas"></div>
											<a href="javascript:void(0);" id="view_large" class="map_links" target="blank"><?php echo $this->__('View Larger Map'); ?></a><span class="separator"> || </span><a href="javascript:void(0);" id="get_directions" class="map_links" target="blank"><?php echo $this->__('Get Directions'); ?></a>
									
											<div class="adress-links">				
												<?php foreach ($addressCollection as $address): ?>
													<div class="adress-box"><div class="number"><?php echo $i; ?></div><a href="javascript:void(0);" onClick="codeAddress('<?php echo $address; ?>', '<?php echo $i; ?>', '<?php echo $this->getSkinUrl('groupdeals/images'); ?>');"><?php echo $address; ?></a></div>
													<?php $i++; ?>
												<?php endforeach; ?>
											</div>
										<?php else: ?>
											<b><?php echo $this->getRedeem(); ?></b>
										<?php endif; ?>
									</div>
								<?php endif; ?>
							</div>
	                    </div>
	                </dd>
				<?php endif; ?>
                <?php foreach ($detailedInfoGroup as $alias => $html):?>
	                <?php if ($alias!='facebook_comments' || ($alias=='facebook_comments' && Mage::getModel('groupdeals/facebook_config')->isEnabled() && Mage::getStoreConfig('groupdeals/facebook_connect/enable_facebook_comments')) && $_gdHelper->displayInIe()): ?>
	                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
	                    <dd class="tab-container">
	                        <div class="tab-content"><?php echo $html ?></div>
	                    </dd>
       				<?php endif; ?>
                <?php endforeach;?>
            </dl>
        <?php endif; ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
        
        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
		updateDiscount('<?php echo $_product->getId() ?>');
		<?php if ($_product->getTypeId()=='bundle' && $_product->isSaleable()): ?>bundle.reloadPrice();<?php endif; ?>

		//set the width of facebook comments on load/resize
		<?php if (Mage::getModel('groupdeals/facebook_config')->isEnabled() && Mage::getStoreConfig('groupdeals/facebook_connect/enable_facebook_comments')): ?>
			jQueryGD(window).resize(function() {
			 	jQueryGD(".fb-comments").attr("data-width", jQueryGD(".tab-container.current").width());
			 	FB.XFBML.parse(jQueryGD(".tab-container.current").width()[0]);
			});

			Event.observe(window, 'load', function() {
				jQueryGD(".toggle-tabs li").on( "click", function() {
				    jQueryGD(".fb-comments").attr("data-width", jQueryGD(".tab-container.current").width());
					jQueryGD('.fb_ltr').css({'width':jQueryGD(".tab-container.current").width()});
				});

		 		jQueryGD(".fb-comments").attr("data-width", jQueryGD(".tab-container.current").width());
		 		FB.XFBML.parse(jQueryGD(".tab-container.current").width()[0]);			
			});
		<?php endif; ?>

		function reinitGoogleMaps() {
			setTimeout(function(){
				google.maps.event.trigger(document.getElementById('map_canvas'), 'resize'); 
				<?php if (isset($addressCollection[0]) && $addressCollection[0]!=''): ?>
					codeAddress('<?php echo $addressCollection[0]; ?>', 'A', '<?php echo $this->getSkinUrl('groupdeals/images'); ?>');
				<?php endif; ?>}
			,100);
		}

        jQueryGD('.gd-toggle-content').each(function () {
            var wrapper = jQueryGD(this);

            var hasTabs = wrapper.hasClass('tabs');
            var hasAccordion = wrapper.hasClass('accordion');
            var startOpen = wrapper.hasClass('open');

            var dl = wrapper.children('dl:first');
            var dts = dl.children('dt');
            var panes = dl.children('dd');
            var groups = new Array(dts, panes);

            //Create a ul for tabs if necessary.
            if (hasTabs) {
                var ul = jQueryGD('<ul class="toggle-tabs"></ul>');
                dts.each(function () {
                    var dt = jQueryGD(this);
                    var li = jQueryGD('<li></li>');
                    li.html(dt.html());
                    ul.append(li);
                });
                ul.insertBefore(dl);
                var lis = ul.children();
                groups.push(lis);
            }

            //Add "last" classes.
            var i;
            for (i = 0; i < groups.length; i++) {
                groups[i].filter(':last').addClass('last');
            }

            function toggleClasses(clickedItem, group) {
                var index = group.index(clickedItem);
                var i;
                for (i = 0; i < groups.length; i++) {
                    groups[i].removeClass('current');
                    groups[i].eq(index).addClass('current');
                }
            }

            //Toggle on tab (dt) click.
            dts.on('click', function (e) {
                //They clicked the current dt to close it. Restore the wrapper to unclicked state.
                if (jQueryGD(this).hasClass('current') && wrapper.hasClass('accordion-open')) {
                    wrapper.removeClass('accordion-open');
                } else {
                    //They're clicking something new. Reflect the explicit user interaction.
                    wrapper.addClass('accordion-open');
                }
                toggleClasses(jQueryGD(this), dts);
            });

            //Toggle on tab (li) click.
            if (hasTabs) {
                lis.on('click', function (e) {
                    toggleClasses(jQueryGD(this), lis);
                });
                //Open the first tab.
                lis.eq(0).trigger('click');
            }

            //Open the first accordion if desired.
            if (startOpen) {
                dts.eq(0).trigger('click');
            }

        });
    //]]>
    </script>
</div>
