<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
//<![CDATA[
    var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
    <?php if ($this->helper('groupdeals')->getMagentoVersion()>1800): ?>
	    var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
	    var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
	    var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
	    var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
	<?php endif; ?>
//]]>
</script>
<?php endif; ?>