<?php if (Mage::helper('groupdeals')->isEnabled()): ?>
<div id="gd-popup-wrapper-bkg"></div>
<?php $productIds = $this->getProductIds(); ?>
<div id="gd-popup-container" class="gd-popup-container" onclick="popup.hidePopup();">
	<div id="gd-popup-content" class="gd-popup-content" onclick="popup.runHidePopup = false;">
		<div class="close-corner">
		    <a href="javascript:void(0)" onClick="popup.hidePopup();"><?php echo $this->__('(x) close'); ?></a>
		</div>
		<?php 
		    $crc = $this->getCurrentCrc();
		    $cityCount = 0;
		    $mainUrl = $this->getUrl('groupdeals/product/noDeals');
		    $tabNr = 1;
		    $lastTab = 'tab1';
		    $universalUrl = '';
		?>
		<div class="countries">			
			<?php $countryCollection = $this->getCountryCollection($productIds); ?>
			<ul>
				<li id="country"><span class="title"><?php echo $this->__('Country:'); ?></span></li>
				<?php foreach ($countryCollection as $country): ?>
					<?php if ($crc['country']!=''): ?>
						<li <?php if ($crc['country']==$country['value']): $lastTab = 'tab'.$tabNr; ?>class="tab_hover"<?php else: ?>class="tab"<?php endif; ?> id="tab<?php echo $tabNr; ?>" onClick="popup.nextTab('tab<?php echo $tabNr; ?>')">
							<?php echo $country['label']; ?>
						</li>
					<?php else: ?>
						<li <?php if ($tabNr==1): ?>class="tab_hover"<?php else: ?>class="tab"<?php endif; ?> id="tab<?php echo $tabNr; ?>" onClick="popup.nextTab('tab<?php echo $tabNr; ?>')">
							<?php echo $country['label']; ?>
						</li>
					<?php endif; ?>
					<?php $tabNr++; ?> 
				<?php endforeach; ?>
					
				<?php if ($universalUrl = $this->getCityUrl('Universal')): ?>
					<?php $cityCount++; ?>
					<?php if ($tabNr==1): ?>
					    <?php $mainUrl = $universalUrl; ?>
					<?php endif; ?>				
					<?php if ($crc['country']!=''): ?>
					    <li <?php if ($crc['country']=='Universal'): ?>class="tab_hover"<?php else: ?>class="tab"<?php endif; ?> id="universal" onClick="popup.nextTab('universal')">
				    		<?php echo $this->__('Universal'); ?>
					    </li>
					<?php else: ?>
						<li class="tab">
							<?php echo $this->__('Universal'); ?>
						</li>
					<?php endif; ?>	
				<?php endif; ?>
			</ul>
			<!-- this select is used for mobile devices -->
			<?php 
			    $cityCount = 0;
			    $mainUrl = $this->getUrl('groupdeals/product/noDeals');
			    $tabNr = 1;
			    $lastTab = 'tab1';
			?>
			<select id="countrySelect" onchange="popup.nextTab(jQueryGD(this).find('option:selected').val());">
		    	<?php foreach ($countryCollection as $country): ?>
					<?php if ($crc['country']!=''): ?>
						<option value="tab<?php echo $tabNr; ?>" <?php if ($crc['country']==$country['value']): $lastTab = 'tab'.$tabNr; ?>selected="selected"<?php endif; ?>><?php echo $country['label']; ?></option>
					<?php else: ?>
						<option value="tab<?php echo $tabNr; ?>" <?php if ($tabNr==1): ?>selected="selected"<?php endif; ?>><?php echo $country['label']; ?></option>
					<?php endif; ?>
					<?php $tabNr++; ?> 
				<?php endforeach; ?>

				<?php if ($universalUrl = $this->getCityUrl('Universal')): ?>
					<?php $cityCount++; ?>
					<?php if ($tabNr==1): ?>
					    <?php $mainUrl = $universalUrl; ?>
					<?php endif; ?>				
					<?php if ($crc['country']!=''): ?>
						<option value="universal" <?php if ($crc['country']=='Universal'): ?>selected="selected"<?php endif; ?>><?php echo $this->__('Universal'); ?></option>
					<?php else: ?>
						<option value="universal"><?php echo $this->__('Universal'); ?></option>
					<?php endif; ?>	
				<?php endif; ?>
		    </select>
		</div>
		<div class="regions-cities">
			<?php $tabNr = 1; ?>
			<?php foreach ($countryCollection as $country): ?>
				<?php if ($crc['country']!=''): ?>
				<div id="tab<?php echo $tabNr; ?>_data" class="tab-content <?php if ($crc['country']!=$country['value']): ?>hide<?php endif; ?>">
				<?php else: ?>
				<div id="tab<?php echo $tabNr; ?>_data" class="tab-content <?php if ($tabNr!=1): ?>hide<?php endif; ?>">
				<?php endif; ?>
					<?php $regionCollection = $this->getRegionCollection($country['value'], $productIds); ?>
					<?php $regionNr = 1; foreach ($regionCollection as $region): ?>
						<ul>
							<?php $cityCollection = $this->getCityCollection($region, $productIds); ?>
						    <li class="main-city"><?php echo $region; ?></li>
						    <?php $cityNr = 0; foreach ($cityCollection as $city): $cityNr++; ?>
						    	<?php $cityCount++; ?>
						    	<?php $cityUrl = $this->getCityUrl($city, $region); ?>
						    	<?php if ($tabNr==1 && $cityNr==1): ?>
						    		<?php $mainUrl = $cityUrl; ?>
						    	<?php endif; ?>
						    	<li <?php if ($crc['city']!='' && $crc['city']==$city && $crc['region']==$region): ?>class="city_tab_hover"<?php endif; ?>>
						    	    <a id="city<?php echo $tabNr.$cityNr; ?>" href="<?php echo $cityUrl; ?>">
						    	    	<?php echo $city; ?>
						    	    </a>
						    	</li>
						    <?php endforeach; ?>				
						</ul>	
						<?php if ($regionNr%4 == 0): ?><div class="clearer"></div><?php endif; ?>
						<?php $regionNr++; ?>
					<?php endforeach; ?>
				</div>
			<?php $tabNr++; ?>
			<?php endforeach; ?>
		</div>
	</div>	
	<script type="text/javascript">
	//<![CDATA[
		var popup = new Popup('gd', {lastTab: '<?php echo $lastTab; ?>', cityCount: '<?php echo $cityCount; ?>', mainDealUrl: '<?php echo $mainUrl; ?>', universalUrl: '<?php echo $universalUrl; ?>'});
			popup.isMobile = <?php echo var_export(Mage::helper('groupdeals')->isMobile(), true); ?>;
			popup.isTablet = <?php echo var_export(Mage::helper('groupdeals')->isTablet(), true); ?>;
			popup.ajaxCartLoadingHtml = '<span id="ajax-cart-please-wait" class="please-wait" ><img src="<?php echo $this->getSkinUrl('groupdeals/images/ajax-loader.gif'); ?>" alt="<?php echo $this->__('Please wait...'); ?>" title="<?php echo $this->__('Please wait...'); ?>" class="v-middle" /><span><?php echo $this->__('Please wait...'); ?></span></span>';
	//]]>
	</script>
</div>
<?php endif; ?>
