<?php if (Mage::helper('groupdeals')->isEnabled()): ?>
<?php $city = $this->getCity(); ?>
<div class="block block-subscribe">
    <div class="block-title">		
        <strong><span><?php echo $this->__('Subscriptions') ?></span> 
        <a href="javascript:void(0)" onMouseOver="jQueryGD('#gd-subscriptions-info').show()" onMouseOut="jQueryGD('#gd-subscriptions-info').hide()" class="details" id="gd-subscriptions-info-mark">(?)</a></strong>
		<div id="gd-subscriptions-info">
			<?php echo $this->__('Subscribe to receive updates whenever a new deal is posted, when it reaches it\'s target or when it\'s over.') ?>           
		</div>		
    </div>
    <form action="<?php echo $this->getUrl('groupdeals/subscriber/subscribe') ?>" method="post" id="gd-subscriptions">
        <div class="block-content">			
		  <?php if ($city): ?>         
			<span><label for="email"><?php echo $this->__('Subscribe to %s Deals:', $this->__($city)) ?></label></span>			
            <div class="input-box">
               <input type="text" name="email" id="email" title="<?php echo $this->__('Subscribe to %s Deals:', $this->__($city)) ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
		  <?php else: ?>
			<?php echo $this->__('Please <a href="javascript:void(0)" onclick="%s">select a city</a> in order to subscribe.', 'popup.showPopup()') ?>
		  <?php endif; ?>
        </div>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var groupdealSubscriberForm = new VarienForm('gd-subscriptions');
    //]]>
    </script>
</div>
<?php endif; ?>
